commands_restrictions:
  dequeue:
    conditions:
      - or:
          - sender-permission >= write
          - sender = biv-agent[bot]
  queue:
    conditions:
      - or:
          - sender-permission >= write
          - sender = biv-agent[bot]

merge_queue:
  checking_label: mergify-checking
  dequeued_label: mergify-dequeued
  max_parallel_checks: 1
  mode: serial
  queued_label: mergify-queued
  reset_on_external_merge: always
  status_comments: outcomes

queue_rules:
  - name: default
    queue_conditions:
      - base = main
      - -draft
      - check-success = linear-link / check
    merge_conditions:
      - check-success = ci
      - check-success = linear-link / check
    batch_size: 1
    branch_protection_injection_mode: merge
    checks_timeout: auto
    max_checks_retries: 0
    merge_method: squash
    update_method: merge
